### ISSUE TITLE
May you open source your code in Actor-Supervision Spatiotemporal Action Localization? THX

### ISSUE THREAD

**Issue by ShawnSu2011** [escorciav/roi_pooling#10]

**Comment by ShawnSu2011** [comment]
Hi, Victor. Your work is impressive and inspiring. May you release your code so I can reproduce your work? Thx

**Comment by escorciav** [comment]
Addressed by email

**Comment by ShawnSu2011** [comment]
Thank You Victor!
My email is su_shaowen@foxmail.com
