### ISSUE TITLE
trying to undestand the output dimension of roi pooling

### ISSUE THREAD

**Issue by Gepeng18** [escorciav/roi_pooling#11]
Thank you for your code, I have a qustion to understand this code.
I have seen the issue  > https://github.com/escorciav/roi_pooling/issues/6 , but i still have quesions about this.

In "example.py" , the input dimention is torch.Size([4, 4, 12, 8]), and the output dimension is torch.Size([4, 4, 5, 7]).
I see "x_np = np.arange(batch_size \* n_channels \* input_size[0] \* input_size[1], dtype=np.float32) " .
I guess that the input means that the number of feature maps is  "4" , and the dimension of every feature map is "4\*12\*8" .  
So the output dimension should be "4 (the number of feature maps) \* 4 (roi_num) \* 4\*5\*7 (feature map dimension after roi pooling)". It means that the dimension of every feature map after roi_pooling is "4 (roi_num) \*4\*5\*7" , and the number of  feature maps is "4". 
So the result should be  "4\*4\*4\*5\*7"  

But your output dimension is torch.Size([4, 4, 5, 7]). I dont know about this.  If that's the case, let's say that the input dimension is torch.Size([100, 4, 12, 8]), "100" means 100 samples. And the output dimension still is torch.Size([4, 4, 5, 7]), and the number of samples has been removed.

Hope you can help, thank you very much.

**Comment by escorciav** [comment]
Thanks for your interest in this. I'm sorry for the late reply, but I was on holiday.

The output tensor is created [here](https://github.com/escorciav/roi_pooling/blob/master/roi_pooling/functions/roi_pooling.py#L210). That plus [the documentation](https://github.com/escorciav/roi_pooling/blob/master/roi_pooling/modules/roi_pooling.py#L22-L31) should help you to understand the ROI operation.

It seems that I forgot to describe the output, my bad. I haven't used this code in a while. Check the FAQ for details of why I released this.
