### ISSUE TITLE
About the format of rois

### ISSUE THREAD

**Issue by harlanhong** [escorciav/roi_pooling#7]
![image](https://user-images.githubusercontent.com/19970321/57175090-29ed6500-6e7a-11e9-8c06-9a9e51935f27.png),
Does your roi format be [index, xMin, yMin, xMax, yMax] or [index, yMin, xMin, yMax, xMax]?

**Comment by escorciav** [comment]
Thanks for your interest. I believe is `[index, xmin, ymin, xmax, ymax]`.

I am sorry, but I don't understand what you meant with the figure. Maybe, the [documentation](https://github.com/escorciav/roi_pooling/blob/master/roi_pooling/functions/roi_pooling.py#L188-L196) can help.

**Comment by escorciav** [comment]
Closed for inactivity
