### ISSUE TITLE
How to use RoIpooling for a particular application

### ISSUE THREAD

**Issue by djongpo** [escorciav/roi_pooling#8]
I am implementing the paper 'Perceptual GAN for small object detection` where I need to do RoI pooling on a feature map with the RoI bounding box coordinates already known. The main architecture is given as follows:
![Capture2](https://user-images.githubusercontent.com/52217535/60412365-6f19e300-9bee-11e9-835f-3863b3b7e126.PNG)
 
Can you tell what modifications to bring in your code to do the same. I am trying to modify `example.py` like this:

`import numpy as np`
`from roi_pooling.functions.roi_pooling import roi_pooling_2d`
`model = VGG16()`
`feature_map=model.predict(img)`

`feature_map = np.asarray(feature_map, dtype='float32')`
`feature_map = feature_map.cuda()`

`rois = torch.FloatTensor([
    [0, 0, 0, 1, 3],
    [0, 2, 2, 3, 3],
    [0, 1, 0, 3, 2]
])`

`rois= rois.cuda()`

`rpooling = roi_pooling_2d(feature_map, rois, (7, 7),spatial_scale=0.6)`

Thanks in advance. Waiting for a reply.

**Comment by escorciav** [comment]
Thanks for your interest in our work.

- That's not an issue related to the code. Thus, I will update the title.

-  I'm not familiar with the paper mentioned above so can't provide feedback. Sorry for that.

- As the question isn't referring to an issue, I close the issue

I might try to take a look at it later as time permits.
